title: nDNA - Neural DNA Framework
email: your-email@example.com
description: >-
  nDNA—Neural DNA—is a novel framework for analyzing the latent cognitive 
  structure of large AI models, mapping how they internalize, evolve, and 
  transmit abstract patterns of thought, reasoning, and belief.
baseurl: "/nDNA"
url: "https://pragyaai.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# Include pages
include:
  - _pages
  - _llm
  - _mfm
  - _t2i
  - _diffusion
  - _efm

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
